### ISSUE TITLE
Using phuel/tables_extended markdown extension with mkdocs does not work due to built-in table extension

### ISSUE THREAD

**Issue by pideu-mh** [phuel/tables_extended#1]
Please check out https://github.com/mkdocs/mkdocs/issues/2771 where I filed an issue because I thought this was a problem that has to be fixed on the mkdocs side.

It seems that the sensible way to fix this problem is to increase the priority of this extension so that it gets called before the built-in table extension. 

What do you think of this change?

**Comment by pideu-mh** [comment]
I saw that you committed https://github.com/phuel/tables_extended/commit/8ad229e479cd9f0eaa9cfd03e216d3db532e40a2 which increases the priority for the markdown registration. Thank you very much!

I noticed that you increased the version number to v1.1, so I thought you did a new release. But there is no new version, however the latest release from last year is already labeled v1.1.

Do you plan to do release a new version and will it be v1.2 then?

**Comment by phuel** [comment]
Sorry, completely forgot the release. I increased the version to v1.2 and released it.

**Comment by pideu-mh** [comment]
I can confirm that everything now works correctly. 

I re-installed my mkdocs environment and used the new v1.2 plugin and everything now works out-of-the-box.

Thank you for your effort!
